version: "3.8"

services:
  prometheus-receiver:
    image: prom/prometheus:latest
    container_name: prometheus_receiver
    volumes:
      - ./prometheus/receiver.yml:/etc/prometheus/prometheus.yml
      - prometheus_receiver_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
    ports:
      - "9090:9090"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9090/-/healthy || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  prometheus-sender-v1:
    image: prom/prometheus:latest
    container_name: prometheus_sender_v1
    volumes:
      - ./prometheus/sender-v1.yml:/etc/prometheus/prometheus.yml
      - prometheus_sender_v1_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9091:9091"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9091/-/healthy || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  prometheus-sender-v2:
    image: prom/prometheus:latest
    container_name: prometheus_sender_v2
    volumes:
      - ./prometheus/sender-v2.yml:/etc/prometheus/prometheus.yml
      - prometheus_sender_v2_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9092/-/healthy || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  avalanche:
    build:
      context: /Users/moekamishima/oss/lfx/avalanche
      dockerfile: Dockerfile
    container_name: prometheus_avalanche
    ports:
      - "9001:9001"
    deploy:
      resources:
        limits:
          memory: 2g

volumes:
  prometheus_receiver_data:
  prometheus_sender_v1_data:
  prometheus_sender_v2_data:
