global:
  external_labels:
    role: "receiver"

scrape_configs:
  - job_name: self
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "avalanche"
    static_configs:
      - targets: ["docker.for.mac.localhost:9001"]
